### ISSUE TITLE
How can we disable the right click?

### ISSUE THREAD

**Issue by mauscoelho** [THEOplayer/docs#3]
**The simple way is disable the feature `context menu`**

As an alternative.

Include it AFTER the call to THEOplayer ui.css, either:
a) in a style element (see below) or
b) in an external style.

See example:

```html
<link rel="stylesheet" type="text/css" href="/path/to/ui.css" />
<style>
  .theo-context-menu {
    display: none;
  }
</style>
```

**Comment by TimLeenaers** [comment]
Thanks, I followed this sample and could disable the right click
